import { cva, type VariantProps } from "class-variance-authority";
import type { ComponentProps } from "react";
import { cn } from "@/lib/utils";

/**
 * The button.
 *
 * Hand-written against `class-variance-authority` rather than generated by the
 * shadcn CLI, because the generated version imports `@radix-ui/react-slot` for
 * an `asChild` prop this application does not use — and a primitive that pulls
 * in a dependency nothing calls is a dependency that can break the build.
 *
 * **No focus ring here.** `app/globals.css` sets `:focus-visible` for every
 * element in the application, deliberately (FR-057): a per-component ring is one
 * more place to forget it, and the failure is invisible to an automated check
 * and fatal to a keyboard user.
 */
const buttonVariants = cva(
  "inline-flex items-center justify-center gap-2 rounded-md text-sm font-medium transition-colors disabled:pointer-events-none disabled:opacity-60 [&_svg]:size-4 [&_svg]:shrink-0",
  {
    variants: {
      variant: {
        default: "bg-accent text-accent-foreground hover:opacity-90",
        outline: "border bg-background hover:bg-muted",
        ghost: "hover:bg-muted",
        destructive: "bg-destructive text-destructive-foreground hover:opacity-90",
      },
      size: {
        default: "h-9 px-4 py-2",
        sm: "h-8 px-3 text-xs",
        icon: "size-9",
      },
    },
    defaultVariants: { variant: "default", size: "default" },
  },
);

/**
 * `ComponentProps<"button">` rather than `ButtonHTMLAttributes`: React 19 passes
 * `ref` as an ordinary prop, and a component that moves focus to itself — the
 * removal confirmation does — needs to accept one. `HTMLAttributes` would have
 * type-checked the markup and refused the ref.
 */
export interface ButtonProps extends ComponentProps<"button">, VariantProps<typeof buttonVariants> {}

export function Button({ className, variant, size, type, ...props }: ButtonProps) {
  return (
    // `type="button"` by default: a button inside a form that submits when it is
    // meant to *cancel* is a data-loss bug that no type checker reports.
    <button type={type ?? "button"} className={cn(buttonVariants({ variant, size }), className)} {...props} />
  );
}

export { buttonVariants };