"""initial schema: nine registry tables

Revision ID: eca01b2db9db
Revises:
Create Date: 2026-09-29 21:13:34.228316

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "eca01b2db9db"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evaluation_questions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("difficulty", sa.String(), nullable=False),
        sa.Column("is_unsupported", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("expected_product", sa.String(), nullable=True),
        sa.Column("expected_category", sa.String(), nullable=True),
        sa.Column("expected_heading_path", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("expected_topics", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("answer_notes", sa.Text(), nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("dataset_version", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('simple_lookup', 'multi_part', 'cross_product', 'troubleshooting', 'permissions', 'api', 'ambiguous', 'unsupported')",
            name="ck_evaluation_questions_category",
        ),
        sa.CheckConstraint(
            "difficulty IN ('easy', 'medium', 'hard')", name="ck_evaluation_questions_difficulty"
        ),
        sa.CheckConstraint("question <> ''", name="ck_evaluation_questions_question_non_empty"),
        sa.CheckConstraint(
            "cardinality(expected_topics) > 0", name="ck_evaluation_questions_topics_non_empty"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "evaluation_runs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dataset_version", sa.String(), nullable=False),
        sa.Column("dataset_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("config_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("question_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("thresholds", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("gate_outcome", sa.String(), nullable=False),
        sa.Column("gate_failures", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("corpus_document_count", sa.Integer(), nullable=True),
        sa.Column("corpus_unit_count", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "gate_outcome IN ('pass', 'fail')", name="ck_evaluation_runs_gate_outcome"
        ),
        sa.CheckConstraint(
            "finished_at IS NULL OR finished_at >= started_at", name="ck_evaluation_runs_time_order"
        ),
        sa.CheckConstraint(
            "question_count >= 0", name="ck_evaluation_runs_question_count_non_negative"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "query_logs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("outcome", sa.String(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("refusal_reason", sa.Text(), nullable=True),
        sa.Column("detected_product", sa.String(), nullable=True),
        sa.Column("detected_category", sa.String(), nullable=True),
        sa.Column("intent", sa.String(), nullable=True),
        sa.Column(
            "classification_confidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("rewrite_queries", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("applied_filters", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("candidates_retrieved", sa.Integer(), server_default="0", nullable=False),
        sa.Column("candidates_reranked", sa.Integer(), server_default="0", nullable=False),
        sa.Column("evidence_selected", sa.Integer(), server_default="0", nullable=False),
        sa.Column("stage_latency_ms", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("total_latency_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column("provider", sa.String(), nullable=True),
        sa.Column("model", sa.String(), nullable=True),
        sa.Column("token_usage", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rerank_model", sa.String(), nullable=True),
        sa.Column("pipeline_trace", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(outcome = 'answered' AND answer IS NOT NULL AND refusal_reason IS NULL) OR (outcome = 'refused' AND answer IS NULL AND refusal_reason IS NOT NULL) OR (outcome = 'error' AND answer IS NULL)",
            name="ck_query_logs_outcome_payload",
        ),
        sa.CheckConstraint(
            "outcome IN ('answered', 'refused', 'error')", name="ck_query_logs_outcome"
        ),
        sa.CheckConstraint("total_latency_ms >= 0", name="ck_query_logs_latency_non_negative"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_query_logs_created_at", "query_logs", ["created_at"], unique=False)
    op.create_table(
        "sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("start_url", sa.Text(), nullable=False),
        sa.Column("allowed_domains", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("product_domain", sa.String(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("status", sa.String(), server_default="active", nullable=False),
        sa.Column("last_crawl_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("manifest_version", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("name <> ''", name="ck_sources_name_non_empty"),
        sa.CheckConstraint(
            "product_domain IS NULL OR product_domain IN ('jira', 'confluence', 'jsm', 'developer')",
            name="ck_sources_product_domain",
        ),
        sa.CheckConstraint("start_url <> ''", name="ck_sources_start_url_non_empty"),
        sa.CheckConstraint("status IN ('active', 'disabled', 'error')", name="ck_sources_status"),
        sa.CheckConstraint(
            "cardinality(allowed_domains) > 0", name="ck_sources_allowed_domains_non_empty"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("start_url"),
    )
    op.create_table(
        "crawl_jobs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("target_url", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), server_default="queued", nullable=False),
        sa.Column(
            "requested_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pages_discovered", sa.Integer(), server_default="0", nullable=False),
        sa.Column("pages_processed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("pages_unchanged", sa.Integer(), server_default="0", nullable=False),
        sa.Column("pages_skipped", sa.Integer(), server_default="0", nullable=False),
        sa.Column("pages_failed", sa.Integer(), server_default="0", nullable=False),
        sa.Column("skipped_reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("scope_prefix", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'completed', 'completed_with_errors', 'failed', 'cancelled')",
            name="ck_crawl_jobs_status",
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "crawl_jobs_one_active_per_source",
        "crawl_jobs",
        ["source_id"],
        unique=True,
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.create_index(
        "ix_crawl_jobs_source_requested", "crawl_jobs", ["source_id", "requested_at"], unique=False
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("canonical_url", sa.Text(), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("product", sa.Text(), nullable=True),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("page_type", sa.Text(), nullable=True),
        sa.Column("language", sa.Text(), nullable=True),
        sa.Column("content_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("source_modified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_crawled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("unit_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("state", sa.String(), server_default="discovered", nullable=False),
        sa.Column("state_detail", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("vectors_live", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tombstoned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state <> 'deleted' OR vectors_live = false", name="ck_documents_deleted_has_no_vectors"
        ),
        sa.CheckConstraint(
            "state IN ('discovered', 'crawling', 'processed', 'indexed', 'failed', 'deleted')",
            name="ck_documents_state",
        ),
        sa.CheckConstraint(
            "tombstoned_at IS NULL OR state = 'deleted'",
            name="ck_documents_tombstone_implies_deleted",
        ),
        sa.ForeignKeyConstraint(["source_id"], ["sources.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id", "url", name="uq_documents_source_url"),
    )
    op.create_index(
        "ix_documents_source_live",
        "documents",
        ["source_id"],
        unique=False,
        postgresql_where=sa.text("state != 'deleted'"),
    )
    op.create_index("ix_documents_state", "documents", ["state"], unique=False)
    op.create_index(
        "ix_documents_tombstoned",
        "documents",
        ["tombstoned_at"],
        unique=False,
        postgresql_where=sa.text("tombstoned_at IS NOT NULL"),
    )
    op.create_table(
        "evaluation_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("run_id", sa.UUID(), nullable=False),
        sa.Column("question_id", sa.String(), nullable=False),
        sa.Column("recall_at_5", sa.Float(), nullable=True),
        sa.Column("precision_at_5", sa.Float(), nullable=True),
        sa.Column("mrr", sa.Float(), nullable=True),
        sa.Column("citation_validity", sa.Float(), nullable=True),
        sa.Column("claim_coverage", sa.Float(), nullable=True),
        sa.Column("faithfulness", sa.Float(), nullable=True),
        sa.Column("refused", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("fabricated_fact_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("invalid_citation_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("searched_products", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "fabricated_fact_count >= 0", name="ck_evaluation_results_fabricated_non_negative"
        ),
        sa.CheckConstraint(
            "invalid_citation_count >= 0",
            name="ck_evaluation_results_invalid_citations_non_negative",
        ),
        sa.CheckConstraint(
            "latency_ms IS NULL OR latency_ms >= 0",
            name="ck_evaluation_results_latency_non_negative",
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["evaluation_questions.id"],
        ),
        sa.ForeignKeyConstraint(["run_id"], ["evaluation_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "question_id", name="uq_evaluation_results_run_question"),
    )
    op.create_table(
        "document_units",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("vector_id", sa.Text(), nullable=False),
        sa.Column("text_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("heading_path", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("block_types", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("overlap_tokens", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("ordinal >= 0", name="ck_document_units_ordinal_non_negative"),
        sa.CheckConstraint("overlap_tokens >= 0", name="ck_document_units_overlap_non_negative"),
        sa.CheckConstraint("token_count > 0", name="ck_document_units_token_count_positive"),
        sa.ForeignKeyConstraint(["document_id"], ["documents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "ordinal", name="uq_document_units_document_ordinal"),
        sa.UniqueConstraint("vector_id"),
    )
    op.create_table(
        "citations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("query_log_id", sa.UUID(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("product", sa.String(), nullable=True),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("heading_path", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("retrieval_score", sa.Float(), nullable=True),
        sa.Column("rerank_score", sa.Float(), nullable=True),
        sa.Column("validation_state", sa.String(), server_default="valid", nullable=False),
        sa.Column("validation_note", sa.Text(), nullable=True),
        sa.CheckConstraint("quote <> ''", name="ck_citations_quote_non_empty"),
        sa.CheckConstraint(
            "validation_state IN ('valid', 'stripped', 'repaired')",
            name="ck_citations_validation_state",
        ),
        sa.CheckConstraint("rank > 0", name="ck_citations_rank_positive"),
        sa.CheckConstraint(
            "rerank_score IS NULL OR (rerank_score >= 0.0 AND rerank_score <= 1.0)",
            name="ck_citations_rerank_score_range",
        ),
        sa.CheckConstraint(
            "retrieval_score IS NULL OR (retrieval_score >= 0.0 AND retrieval_score <= 1.0)",
            name="ck_citations_retrieval_score_range",
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["documents.id"],
        ),
        sa.ForeignKeyConstraint(["query_log_id"], ["query_logs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["unit_id"],
            ["document_units.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("query_log_id", "rank", name="uq_citations_query_log_rank"),
    )
    op.create_index(
        "ix_citations_query_log_rank", "citations", ["query_log_id", "rank"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_citations_query_log_rank", table_name="citations")
    op.drop_table("citations")
    op.drop_table("document_units")
    op.drop_table("evaluation_results")
    op.drop_index(
        "ix_documents_tombstoned",
        table_name="documents",
        postgresql_where=sa.text("tombstoned_at IS NOT NULL"),
    )
    op.drop_index("ix_documents_state", table_name="documents")
    op.drop_index(
        "ix_documents_source_live",
        table_name="documents",
        postgresql_where=sa.text("state != 'deleted'"),
    )
    op.drop_table("documents")
    op.drop_index("ix_crawl_jobs_source_requested", table_name="crawl_jobs")
    op.drop_index(
        "crawl_jobs_one_active_per_source",
        table_name="crawl_jobs",
        postgresql_where=sa.text("status IN ('queued', 'running')"),
    )
    op.drop_table("crawl_jobs")
    op.drop_table("sources")
    op.drop_index("ix_query_logs_created_at", table_name="query_logs")
    op.drop_table("query_logs")
    op.drop_table("evaluation_runs")
    op.drop_table("evaluation_questions")
    # ### end Alembic commands ###
