"""T076 — one question against a real corpus, every claim cited (FR-002, SC-018).

This is the only test in the repository that checks the whole claim at once, and
so the only one that can catch a mistake that is invisible at every other seam:
that a fluent, plausible, unsourced answer is reachable. Everything the claim
rests on here is real, because a citation test over a corpus this file wrote
itself proves only that the test agrees with itself.

**Real:** the publisher page is fetched by the real crawler through the real
`POST /sources` endpoint; the chunks are embedded by the real model into a real
index; the answer is generated and verified by the real LLM provider; each
citation is checked against the registry rows this crawl wrote; and each link is
opened by a real HTTP request. The one thing the test does *not* do is assert
anything about the publisher's prose — the corpus is Atlassian's, not ours.

**Isolation.** Vectors go into a dedicated Pinecone namespace (`e2e-t076`) so a
failed run cannot contaminate the `atlassian-public` corpus, and the registry
rows are deleted on the way out rather than truncated, because truncation is
what wipes an operator's live registry. The test refuses to truncate: the whole
point of it is a corpus that other work also depends on.

**Gating.** Three dependencies are required and each missing one skips with an
explicit message rather than a bare `skip`: a live `GROQ_API_KEY` (generation),
a live `PINECONE_API_KEY` (embedding and search), and a reachable PostgreSQL
(`tests/fixtures/database.py` skips with the driver's own refusal text).

**What "every claim is cited" means here.** The response carries citations as a
list, not as inline markers, so the per-claim invariant is checked the way it
actually bites: each citation must (a) name a unit this crawl actually wrote,
(b) carry the registry's own URL for that document, and (c) carry a quote that
is found in the text that was embedded for that unit. A model that invents a
quote fails (c), and a model that cites a URL the registry does not vouch for
fails (b).
"""

from __future__ import annotations

import asyncio
import os
import re
import uuid
from collections.abc import AsyncIterator

import pytest
from httpx import ASGITransport, AsyncClient
from sqlalchemy import delete, select

from tests.fixtures.credentials import has_credential
from tests.fixtures.database import describe_connection_failure, migrate_to_head

pytestmark = [
    pytest.mark.e2e,
    pytest.mark.skipif(
        not has_credential("GROQ_API_KEY"),
        reason=(
            "T076 needs a live Groq account: the answer under test is generated by the "
            "real provider, and a stubbed one would test the stub. No real GROQ_API_KEY."
        ),
    ),
    pytest.mark.skipif(
        not has_credential("PINECONE_API_KEY"),
        reason=(
            "T076 needs a live Pinecone index: the corpus is embedded and searched through "
            "the real store. No real PINECONE_API_KEY."
        ),
    ),
]

#: The publisher page this test crawls. One page, depth 0 — the smallest corpus
#: that can still produce a multi-unit answer, so the test's cost is one request
#: to Atlassian and a handful of embeddings. A page no earlier verification used,
#: so the document is new and its vectors are written rather than reported
#: unchanged: an unchanged page indexes nothing, and a corpus of nothing answers
#: nothing.
START_URL = "https://developer.atlassian.com/cloud/jira/platform/rest/v3/api-group-issues/"

#: The name this test registers its source under, and the handle its own cleanup
#: and re-runs find it by.
SOURCE_NAME = "T076 e2e corpus"

#: Answerable from the page above, in the page's own terms. A question the
#: corpus cannot support is not a harder test of citations; it is a refusal, and
#: a refusal has no claims to check.
QUESTION = "How do you create an issue with the Jira Cloud platform REST API?"

NAMESPACE = "e2e-t076"

CRAWL_TIMEOUT_SECONDS = 300


@pytest.fixture(scope="module", name="_schema")
def _schema() -> None:
    try:
        migrate_to_head()
    except Exception:  # noqa: BLE001 - an absent database is a skip
        pytest.skip(describe_connection_failure())


@pytest.fixture
async def client(_schema: None) -> AsyncIterator[AsyncClient]:
    """An in-process client over the real app, in an isolated namespace."""
    from app.core.config import reset_settings
    from app.db.session import dispose_engine
    from app.main import create_app, lifespan
    from app.retrieval.vector_store import reset_vector_store

    previous_namespace = os.environ.get("PINECONE_NAMESPACE")
    os.environ["PINECONE_NAMESPACE"] = NAMESPACE
    reset_settings()
    reset_vector_store()

    app = create_app(enable_probes=False)
    transport = ASGITransport(app=app)
    try:
        async with lifespan(app):
            async with AsyncClient(transport=transport, base_url="http://t") as http:
                yield http
    finally:
        await _clear_namespace()
        if previous_namespace is None:
            os.environ.pop("PINECONE_NAMESPACE", None)
        else:
            os.environ["PINECONE_NAMESPACE"] = previous_namespace
        reset_settings()
        reset_vector_store()
        await dispose_engine()


async def _clear_namespace() -> None:
    """Remove this test's vectors. Never touches another namespace."""
    from app.core.logging import get_logger
    from app.retrieval.vector_store import get_vector_store

    try:
        await get_vector_store().delete_namespace(namespace=NAMESPACE)
    except Exception as exc:  # noqa: BLE001 - a cleanup failure is not the test's subject
        # Loud, but not fatal: turning a failed assertion into a teardown error
        # hides the real one, and silently leaving vectors behind would be worse.
        # The namespace is isolated and named, so the message says exactly what
        # to remove.
        get_logger("tests.e2e").warning(
            f"T076 could not clear namespace {NAMESPACE}; delete it by hand: {exc}"
        )


#: Names this test is allowed to delete without asking. Anything else registered
#: on `START_URL` belongs to an operator, and this test refuses to remove it —
#: a test that quietly deletes someone's corpus is worse than a test that stops.
OWNED_NAMES = frozenset({SOURCE_NAME, "e2e-debug corpus"})


async def _purge_previous_run() -> None:
    """Remove a previous run's rows, so this run's crawl is a new document.

    `POST /sources` is idempotent by `start_url` by design, so a second run gets
    the first run's source back with no `crawl_job` and no new vectors — and an
    unchanged page indexes nothing, so the corpus would be empty and the test
    would refuse a question the page answers. Deleting the rows first is what
    makes the run repeatable.

    Rows are deleted outright rather than transitioned to `deleted` the way the
    product does: the vectors they point at live only in this test's namespace,
    which is wiped wholesale either way, and a soft transition here would leave
    a tombstoned row behind that no operator ever asked for.
    """
    from app.db.models import Document, DocumentUnit, Source
    from app.db.session import get_session_factory

    factory = get_session_factory()
    async with factory() as session:
        rows = (
            await session.execute(select(Source).where(Source.start_url == START_URL))
        ).scalars()
        occupants = list(rows)
        foreign = [s for s in occupants if s.name not in OWNED_NAMES]
        assert not foreign, (
            f"{START_URL} is registered to a source this test does not own "
            f"({foreign[0].name!r}); point T076 at another page or remove it yourself"
        )
        stale = [s.id for s in occupants]
        if not stale:
            return
        doc_ids = (
            await session.execute(select(Document.id).where(Document.source_id.in_(stale)))
        ).scalars()
        await session.execute(delete(DocumentUnit).where(DocumentUnit.document_id.in_(doc_ids)))
        await session.execute(delete(Document).where(Document.source_id.in_(stale)))
        await session.execute(delete(Source).where(Source.id.in_(stale)))
        await session.commit()


async def _remove_run(source: uuid.UUID) -> None:
    from app.db.models import Document, DocumentUnit, Source
    from app.db.session import get_session_factory

    factory = get_session_factory()
    async with factory() as session:
        doc_ids = (
            await session.execute(select(Document.id).where(Document.source_id == source))
        ).scalars()
        await session.execute(delete(DocumentUnit).where(DocumentUnit.document_id.in_(doc_ids)))
        await session.execute(delete(Document).where(Document.source_id == source))
        await session.execute(delete(Source).where(Source.id == source))
        await session.commit()


async def _wait_until_searchable(question: str, *, timeout_seconds: int = 90) -> int:
    """Block until the freshly written corpus answers a search, and report the wait.

    Measured on 2026-10-04: a crawl job reported `completed` — every upsert
    acknowledged — and a search issued immediately afterwards returned zero
    hits. The index is eventually consistent, so "the writes were accepted" and
    "the writes are queryable" are different moments, and only the second one can
    answer a question. The delay is returned rather than logged so a slow
    consistency window shows up in the test's own output instead of only in a
    vendor's dashboard.

    This waits for the *index*, not for the answer: the question is unchanged
    from the one the test will ask, so a corpus that can never satisfy it fails
    here too rather than as a mysterious refusal later.
    """
    from app.retrieval.vector_store import get_vector_store

    store = get_vector_store()
    started = asyncio.get_running_loop().time()
    while True:
        hits = await store.search(query=question, top_k=1, namespace=NAMESPACE)
        waited = int(asyncio.get_running_loop().time() - started)
        if hits:
            return waited
        if waited >= timeout_seconds:
            pytest.fail(
                f"the crawl finished but its vectors were still not searchable after "
                f"{waited}s; the index never surfaced this corpus"
            )
        await asyncio.sleep(2)


@pytest.fixture
async def source_id(client: AsyncClient) -> AsyncIterator[uuid.UUID]:
    """Crawl one real page through the real endpoint, then wait for the job."""
    await _purge_previous_run()
    response = await client.post(
        "/api/v1/sources",
        json={
            "name": SOURCE_NAME,
            "start_url": START_URL,
            "product_domain": "jira",
            "max_pages": 2,
            "max_depth": 0,
            "delay_seconds": 0.5,
        },
    )
    assert response.status_code == 201, (
        f"the corpus source was not created, so there is no corpus: {response.text}"
    )
    created = response.json()
    job = created.get("crawl_job")
    assert job is not None, f"the crawl did not start: {created}"
    job_id = job["id"]

    deadline = asyncio.get_running_loop().time() + CRAWL_TIMEOUT_SECONDS
    status = job.get("status")
    while status in ("pending", "running"):
        if asyncio.get_running_loop().time() > deadline:
            pytest.fail(f"the T076 crawl did not finish within {CRAWL_TIMEOUT_SECONDS}s")
        await asyncio.sleep(2)
        polled = await client.get(f"/api/v1/crawl-jobs/{job_id}")
        assert polled.status_code == 200, polled.text
        status = polled.json()["status"]

    assert status == "completed", f"the T076 crawl ended {status}: {polled.text}"

    waited = await _wait_until_searchable(QUESTION)
    if waited:
        print(f"\nT076: the index surfaced the crawl after {waited}s (eventual consistency)")

    # Only this test's rows go. The rest of the registry is an operator's work,
    # and `truncate_all` would destroy it — see the module docstring.
    the_id = uuid.UUID(created["source"]["id"])
    yield the_id
    await _remove_run(the_id)


async def _registry_unit(unit_id: str) -> tuple[str, str, str] | None:
    """`(document_id, vector_id, document_url)` for one unit, or None."""
    from app.db.models import Document, DocumentUnit
    from app.db.session import get_session_factory

    factory = get_session_factory()
    async with factory() as session:
        row = (
            await session.execute(select(DocumentUnit).where(DocumentUnit.id == uuid.UUID(unit_id)))
        ).scalar_one_or_none()
        if row is None:
            return None
        document = (
            await session.execute(select(Document).where(Document.id == row.document_id))
        ).scalar_one_or_none()
        if document is None:
            return None
        return str(row.document_id), row.vector_id, document.url


def _significant_tokens(text: str) -> set[str]:
    return set(re.findall(r"[a-z0-9]{4,}", text.lower()))


async def _link_opens(url: str) -> bool:
    """One real request to the publisher, with the crawler's own identity."""
    import httpx
    from app.core.config import get_settings

    settings = get_settings()
    async with httpx.AsyncClient(
        timeout=20.0,
        follow_redirects=True,
        headers={"User-Agent": settings.crawl_user_agent, "Accept": "text/html"},
    ) as client:
        try:
            response = await client.get(url)
        except httpx.HTTPError:
            return False
    return response.status_code < 400


class TestCitedAnswer:
    async def test_a_question_about_the_crawled_corpus_is_answered_and_cited(
        self, client: AsyncClient, source_id: uuid.UUID
    ) -> None:
        response = await client.post("/api/v1/chat", json={"question": QUESTION})
        assert response.status_code == 200, response.text
        body = response.json()

        assert body["outcome"] == "answered", (
            f"the corpus could not answer the question, so T076 proved nothing: {body}"
        )
        assert body["answer"], "an answered outcome with no answer text"
        assert body["citations"], "an answer with no citation carries no claim support (FR-002)"

        from app.retrieval.vector_store import get_vector_store

        store = get_vector_store()
        for citation in body["citations"]:
            registry = await _registry_unit(citation["unit_id"])
            assert registry is not None, (
                f"citation {citation['rank']} names unit {citation['unit_id']}, which the "
                "registry does not contain — the link was not resolved through the record (FR-004)"
            )
            document_id, vector_id, document_url = registry
            assert citation["document_id"] == document_id, (
                "the citation's document does not own the unit it cites"
            )
            assert citation["source_url"] == document_url, (
                f"citation link {citation['source_url']} is not the registry's url "
                f"{document_url} for that document — a link not taken from the record of "
                "truth is a link nobody can check (FR-004, FR-050)"
            )
            assert citation["validation_state"] in ("valid", "repaired"), (
                f"a {citation['validation_state']} citation reached the client"
            )

            quote = citation.get("quote") or ""
            assert quote, f"citation {citation['rank']} carries no supporting quote"
            records = await store.fetch([vector_id], namespace=NAMESPACE)
            assert records, f"citation {citation['rank']} names a unit with no indexed text"
            unit_text = records[0].text
            quote_tokens = _significant_tokens(quote)
            unit_tokens = _significant_tokens(unit_text)
            overlap = len(quote_tokens & unit_tokens) / len(quote_tokens) if quote_tokens else 0.0
            assert overlap >= 0.6, (
                f"citation {citation['rank']} quotes text that is not in the unit it cites "
                f"(token overlap {overlap:.2f}): {quote!r}"
            )

        links = sorted({c["source_url"] for c in body["citations"]})
        for link in links:
            assert await _link_opens(link), f"the citation link {link} does not open"
